spring:
  jpa:
    database: mysql
    show-sql: true
  datasource:
    platform: mysql
    hikari:
      maximum-pool-size: 5

  flyway:
    enabled: false
  web:
    resources:
      cache:
        period: 126227704


info:
  app:
    name: Comment it
    description: jvm based backend server
    version: 1.0.1

management:
  endpoint:
    health:
      enabled: true

  endpoints:
    web:
      base-path: /

server:
  port: 3000


